/taxtion
    /static
        /assets
            /logo
                logo_tax.jpeg
            /stock_images
                (your images)
            /generated_images
                (your images)
        /css
            styles.css
        /js
            script.js
    /includes
        header.php
        footer.php
    /pages
        index.php
        about.php
        contact.php
        countries.php
        services.php
        saudi.php
        qatar.php
        oman.php
        india.php
        hongkong.php
        bahrain.php
    .htaccess